AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless WebApi

Globals:
  Function:
    Timeout: 30

Resources:
  ServerlessWebApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ServerlessWebApi
      CodeUri: DynamoTest/bin/Debug/netcoreapp2.1/publish
      MemorySize: 1024
      Policies: 
        - Statement:
          - Action: [ "secretsmanager:GetSecretValue" ]
            Effect: Allow
            Resource: "arn:aws:secretsmanager:us-west-2:809794767795:secret:dynamo_iam_user-XN2bM3"
            #Resource: "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:dynamo_iam_user-XN2bM3"
        - AWSLambdaFullAccess
      Handler: DynamoTest::DynamoTest.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore2.1
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
